"""Generate .agents/.worktree-services.toml for service orchestration."""

from ..detectors.base import ProjectDetectionResults
from ..typing_defs import InstallAnswers

# Service name patterns for port assignment
SERVER_PATTERNS = ("server", "api", "backend", "app")
WEBUI_PATTERNS = ("web", "webui", "frontend", "client", "ui", "studio")

# Default port values
DEFAULT_SERVER_PORT = 19091
DEFAULT_WEBUI_PORT = 19071


def _parse_port(value: str, default: int) -> int:
    """Parse port string to int with validation.

    Returns default if value is not a valid port number (1-65535).
    """
    try:
        port = int(value)
        if not 1 <= port <= 65535:
            return default
        return port
    except ValueError:
        return default


def _format_service_name(name: str) -> str:
    """Format service name for display.

    Converts snake_case and kebab-case to Title Case.
    Example: "web_ui" -> "Web UI", "my-api" -> "My API"
    """
    return name.replace("_", " ").replace("-", " ").title()


def generate_services_config(
    answers: InstallAnswers,
    detection_results: ProjectDetectionResults,
) -> str:
    """Generate services config for Docker orchestration."""
    infra = detection_results.get("infrastructure")

    # Get Docker prefix from answers or derive from project
    docker_prefix = answers.get("docker_prefix", "myproject")

    # Get base ports from answers or use defaults with validation
    server_port = _parse_port(
        answers.get("base_server_port", str(DEFAULT_SERVER_PORT)),
        DEFAULT_SERVER_PORT,
    )
    webui_port = _parse_port(
        answers.get("base_webui_port", str(DEFAULT_WEBUI_PORT)),
        DEFAULT_WEBUI_PORT,
    )

    # Get runtime preference from answers
    runtime = answers.get("container_runtime", "auto")

    # Parse Docker services if available
    services: list[dict[str, str]] = []
    if infra and "docker_services" in infra.details:
        service_names = infra.details["docker_services"].split(",")
        services = _generate_service_definitions(service_names)

    return _render_services_config(docker_prefix, server_port, webui_port, services, runtime)


def _generate_service_definitions(
    service_names: list[str],
) -> list[dict[str, str]]:
    """Generate service definitions from detected Docker services."""
    if not service_names:
        return [
            {"name": "Server", "port_key": "server", "health_path": "/health"},
            {"name": "Web UI", "port_key": "webui", "health_path": "/"},
        ]

    return [_create_service_definition(name) for name in service_names]


def _create_service_definition(name: str) -> dict[str, str]:
    """Create a service definition based on name pattern matching."""
    name_lower = name.lower()
    formatted_name = _format_service_name(name)

    # Determine port and health path based on service name pattern
    if any(pattern in name_lower for pattern in WEBUI_PATTERNS):
        return {"name": formatted_name, "port_key": "webui", "health_path": "/"}

    # Default to server-like service (includes SERVER_PATTERNS and unknown)
    return {"name": formatted_name, "port_key": "server", "health_path": "/health"}


def _render_services_config(
    docker_prefix: str,
    server_port: int,
    webui_port: int,
    services: list[dict[str, str]],
    runtime: str = "auto",
) -> str:
    """Render the services configuration file."""
    lines = [
        "# Worktree Service Orchestration Configuration",
        "# Generated by worktree-flow install",
        "# See: skills/worktree-flow/docs/service-configuration.md",
        "",
        "[docker]",
        f'prefix = "{docker_prefix}"',
        f'runtime = "{runtime}"  # "auto", "docker", or "podman"',
        "",
        "[ports]",
        f"server = {server_port}",
        f"webui = {webui_port}",
        "",
    ]

    for service in services:
        lines.append("[[services]]")
        lines.append(f'name = "{service["name"]}"')
        lines.append(f'port_key = "{service["port_key"]}"')
        lines.append(f'health_path = "{service["health_path"]}"')
        lines.append("")

    return "\n".join(lines)
