"""Generate scripts/worktree-setup.sh based on project detection."""

from worktree_flow.lib.container_runtime import RuntimeType, get_runtime

from ..detectors.base import DetectionResult, ProjectDetectionResults
from ..typing_defs import InstallAnswers


def generate_setup_script(
    answers: InstallAnswers,
    detection_results: ProjectDetectionResults,
) -> str | None:
    """Generate a setup script based on detected project patterns."""
    pkg_mgr = detection_results.get("package_managers")
    build_tools = detection_results.get("build_tools")
    infra = detection_results.get("infrastructure")

    # Determine install commands
    install_commands = _get_install_commands(pkg_mgr)
    build_commands = _get_build_commands(build_tools, pkg_mgr)
    has_docker = bool(infra and "docker" in infra.details)

    # Determine compose command based on available runtime
    compose_command = "docker compose"  # Default
    runtime_pref: RuntimeType = answers.get("container_runtime", "auto")  # type: ignore[assignment]
    runtime = get_runtime(runtime_pref)
    if runtime:
        compose_command = " ".join(runtime.compose_command)

    return _render_setup_script(install_commands, build_commands, has_docker, compose_command)


def _get_install_commands(pkg_mgr: DetectionResult | None) -> list[str]:
    """Get dependency installation commands."""
    if not pkg_mgr:
        return []

    commands: list[str] = []
    details = pkg_mgr.details

    # JavaScript: prioritize modern package managers
    js_commands = {
        "bun": "bun install",
        "pnpm": "pnpm install",
        "yarn": "yarn install",
        "npm": "npm install",
    }
    for key, cmd in js_commands.items():
        if key in details:
            commands.append(cmd)
            break

    # Python: prefer uv over pip
    if "uv" in details:
        commands.append("uv sync")
    elif "pip" in details:
        commands.append("pip install -r requirements.txt")

    # Rust
    if "cargo" in details:
        commands.append("cargo build")

    return commands


def _get_build_commands(
    build_tools: DetectionResult | None,
    pkg_mgr: DetectionResult | None,
) -> list[str]:
    """Get build commands."""
    commands: list[str] = []

    if not build_tools:
        return commands

    details = build_tools.details

    if "turbo" in details:
        commands.append("turbo run build")
    elif "make" in details:
        targets: list[str] = details.get("makefile_targets", "").split(",")
        if "build" in targets or "ts-build" in targets:
            build_target = "ts-build" if "ts-build" in targets else "build"
            commands.append(f"make {build_target}")

    return commands


def _render_setup_script(
    install_commands: list[str],
    build_commands: list[str],
    has_docker: bool,
    compose_command: str = "docker compose",
) -> str:
    """Render the setup script."""
    lines = [
        "#!/bin/bash",
        "set -e",
        "",
        "# Worktree Setup Script",
        "# Generated by worktree-flow install",
        "",
        'echo "========================================="',
        'echo "  Worktree Setup Script"',
        'echo "========================================="',
        "",
    ]

    # Verify we're in a worktree
    lines.extend(
        [
            "# Verify we're in a worktree",
            'if [ ! -f "worktree-status.toml" ] && [ -z "$SKIP_WORKTREE_CHECK" ]; then',
            '    echo "Warning: No worktree-status.toml found. Run from a worktree directory."',
            "fi",
            "",
        ]
    )

    # Install dependencies
    if install_commands:
        lines.append('echo "[1] Installing dependencies..."')
        for cmd in install_commands:
            lines.append(cmd)
        lines.append('echo "Dependencies installed."')
        lines.append("")

    # Build
    if build_commands:
        lines.append('echo "[2] Building project..."')
        for cmd in build_commands:
            lines.append(cmd)
        lines.append('echo "Build complete."')
        lines.append("")

    # Container services
    if has_docker:
        lines.extend(
            [
                'echo "[3] Starting container services..."',
                "if [ -f docker-compose.yml ] || [ -f compose.yml ]; then",
                f"    {compose_command} up -d",
                '    echo "Container services started."',
                "else",
                '    echo "No compose file found, skipping."',
                "fi",
                "",
            ]
        )

    # Port configuration
    lines.extend(
        [
            "# Detect and save ports",
            'if [ -f ".agents/.worktree-services.toml" ]; then',
            '    echo "[4] Configuring ports..."',
            "    # Port configuration is handled by worktree-flow CLI",
            "fi",
            "",
            'echo "========================================="',
            'echo "  Setup Complete"',
            'echo "========================================="',
        ]
    )

    return "\n".join(lines) + "\n"
