"""Migrate v1 configurations to v2 format."""

import re
from pathlib import Path

from .auditor import AuditReport


class ConfigMigrator:
    """Migrate worktree-flow configuration to latest version."""

    def __init__(self, project_root: Path):
        self.root = project_root
        self.config_path = project_root / ".agents" / ".worktree-config.toml"

    def migrate(self, report: AuditReport, dry_run: bool = False) -> list[str]:
        """Apply migrations based on audit report.

        Returns list of actions taken (or that would be taken if dry_run).
        """
        actions: list[str] = []

        if not self.config_path.exists():
            return actions

        content = self.config_path.read_text()
        modified = content

        # Apply each migration
        modified, migration_actions = self._migrate_cli_paths(modified)
        actions.extend(migration_actions)

        modified, migration_actions = self._add_missing_sections(modified, report)
        actions.extend(migration_actions)

        # Write if modified
        if modified != content and not dry_run:
            self.config_path.write_text(modified)
            actions.append("Wrote updated configuration to .agents/.worktree-config.toml")

        return actions

    def _migrate_cli_paths(self, content: str) -> tuple[str, list[str]]:
        """Update old CLI path patterns to v2."""
        actions = []

        old_patterns = [
            (r'hooks/worktree-state/cli\.py', 'uv run -m worktree_flow.cli'),
        ]

        for old, new in old_patterns:
            if re.search(old, content):
                content = re.sub(old, new, content)
                actions.append(f"Updated CLI path pattern: {old} -> {new}")

        return content, actions

    def _add_missing_sections(self, content: str, report: AuditReport) -> tuple[str, list[str]]:
        """Add missing configuration sections."""
        actions = []

        # Add [validation] if missing
        if "[validation]" not in content:
            validation_section = """
[validation]
typecheck_command = "echo 'Configure typecheck command'"
lint_command = "echo 'Configure lint command'"
test_command = "make test"
require_simplified = false
timeout = 300
"""
            content = content.rstrip() + "\n" + validation_section
            actions.append("Added [validation] section with placeholder commands")

        # Add [lifecycle.hooks] if missing
        if "[lifecycle.hooks]" not in content:
            hooks_section = """
[lifecycle.hooks]
post_init = "skills/worktree-flow/lifecycle/post_init.py"
pre_validate = "skills/worktree-flow/lifecycle/pre_validate.py"
pre_review = "skills/worktree-flow/lifecycle/pre_review.py"
pre_merge = "skills/worktree-flow/lifecycle/pre_merge.py"
pre_cleanup = "skills/worktree-flow/lifecycle/pre_cleanup.py"
"""
            content = content.rstrip() + "\n" + hooks_section
            actions.append("Added [lifecycle.hooks] section")

        # Add [lifecycle.templates] if missing
        if "[lifecycle.templates]" not in content:
            templates_section = """
[lifecycle.templates]
review_request = "skills/worktree-flow/templates/review_request.jinja"
"""
            content = content.rstrip() + "\n" + templates_section
            actions.append("Added [lifecycle.templates] section")

        return content, actions

    def create_services_config(self, docker_prefix: str = "myproject") -> str:
        """Create a basic services config if Docker is detected."""
        services_path = self.root / ".agents" / ".worktree-services.toml"

        if services_path.exists():
            return "Services config already exists"

        # Check for Docker
        compose_files = ["docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"]
        has_docker = any((self.root / f).exists() for f in compose_files)

        if not has_docker:
            return "No Docker Compose file detected, skipping services config"

        content = f'''# Worktree Service Orchestration Configuration
# Generated by worktree-flow optimize

[docker]
prefix = "{docker_prefix}"

[ports]
server = 19091
webui = 19071

[[services]]
name = "Server"
port_key = "server"
health_path = "/health"

[[services]]
name = "WebUI"
port_key = "webui"
health_path = "/"
'''
        services_path.write_text(content)
        return "Created .agents/.worktree-services.toml"
